"""
stage2/blender_exporter.py

Blender Script Exporter
━━━━━━━━━━━━━━━━━━━━━━
Generates a self-contained Python script (``simulation.py``) that can be
run inside Blender to set up and execute the physics simulation.

The script:
  1. Clears the default Blender scene.
  2. Imports each object mesh (.obj) into Blender.
  3. Assigns the correct physics type (Rigid Body / Fluid / Cloth / Soft Body).
  4. Sets numerical physics parameters from the material map.
  5. Creates force fields for each inferred force.
  6. Configures the scene timeline and bakes the physics simulation.
  7. Renders the animation (optional).

No Claude tool-use loop is needed here — the exporter is deterministic
given the structured inputs from Stages 1 and 2.
"""

from __future__ import annotations

import json
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
import config as cfg
from utils.shared import get_logger, save_state

_log = get_logger("stage2.blender_exporter")

# Blender physics type mapping
MATERIAL_TO_BLENDER_TYPE: dict[str, str] = {
    "rigid":      "RIGID_BODY",
    "fluid":      "FLUID",
    "deformable": "CLOTH",   # or SOFT_BODY depending on sub_type
    "granular":   "RIGID_BODY",   # approximated as many rigid particles
}

FORCE_TYPE_TO_BLENDER: dict[str, str] = {
    "gravity":    "GRAVITY",
    "impulse":    "FORCE",
    "sustained":  "FORCE",
    "pressure":   "WIND",
    "explosion":  "EXPLOSION",
    "wind":       "WIND",
    "custom":     "FORCE",
}


class BlenderScriptExporter:
    """Generates a Blender Python script from pipeline outputs."""

    def export(
        self,
        scene: dict,
        material_map: dict[str, dict],
        force_spec: dict,
        run_directory: Path,
        prompt: str = "",
        frame_end: int = 250,
        fps: int = 24,
    ) -> Path:
        """
        Generate ``simulation.py`` in *run_directory* and return its path.
        """
        script = self._build_script(
            scene=scene,
            material_map=material_map,
            force_spec=force_spec,
            run_directory=run_directory,
            prompt=prompt,
            frame_end=frame_end,
            fps=fps,
        )

        out_path = run_directory / cfg.BLENDER_SCRIPT_NAME
        out_path.write_text(script, encoding="utf-8")
        _log.info("Blender script written → %s", out_path)
        return out_path

    # ── internal ──────────────────────────────────────────────────────────────

    def _build_script(
        self,
        scene: dict,
        material_map: dict[str, dict],
        force_spec: dict,
        run_directory: Path,
        prompt: str,
        frame_end: int,
        fps: int,
    ) -> str:
        objects = scene.get("objects", [])
        forces = force_spec.get("forces", [])
        gravity = force_spec.get("gravity", {})

        lines: list[str] = []

        # ── Header ────────────────────────────────────────────────────────────
        lines += [
            '"""',
            "simulation.py — Auto-generated Blender physics simulation script.",
            f"Generated by the Physics Simulation Pipeline.",
            f"Prompt: {prompt}",
            "",
            "Usage:",
            "  blender --background --python simulation.py",
            '"""',
            "",
            "import bpy",
            "import mathutils",
            "import os",
            "",
            "# ── Scene setup ──────────────────────────────────────────────────────────",
            "def clear_scene():",
            "    bpy.ops.object.select_all(action='SELECT')",
            "    bpy.ops.object.delete(use_global=False)",
            "    for collection in bpy.data.collections:",
            "        bpy.data.collections.remove(collection)",
            "",
            "clear_scene()",
            "",
            f"# Frame range",
            f"bpy.context.scene.frame_start = 1",
            f"bpy.context.scene.frame_end = {frame_end}",
            f"bpy.context.scene.render.fps = {fps}",
            "",
        ]

        # ── Gravity ──────────────────────────────────────────────────────────
        if gravity.get("enabled", True):
            g = gravity.get("magnitude", 9.81)
            gd = gravity.get("direction", [0, 0, -1])
            lines += [
                "# ── Gravity ──────────────────────────────────────────────────────────",
                f"bpy.context.scene.use_gravity = True",
                f"bpy.context.scene.gravity = ("
                f"{gd[0] * g:.4f}, {gd[1] * g:.4f}, {gd[2] * g:.4f})",
                "",
            ]

        # ── Rigid Body World ──────────────────────────────────────────────────
        lines += [
            "# ── Physics world setup ─────────────────────────────────────────────────",
            "bpy.ops.rigidbody.world_add()",
            "rbw = bpy.context.scene.rigidbody_world",
            "rbw.substeps_per_frame = 10",
            "rbw.solver_iterations = 10",
            "rbw.time_scale = 1.0",
            "",
        ]

        # ── Import Meshes ─────────────────────────────────────────────────────
        lines += [
            "# ── Import meshes ───────────────────────────────────────────────────────",
            "imported_objects = {}",
            "",
        ]

        for obj in objects:
            label = obj.get("label", "object")
            mesh_path = obj.get("mesh_path", "")
            safe_label = label.replace(" ", "_").lower()
            mat_spec = material_map.get(label, {})
            mat_type = mat_spec.get("material_type", "rigid")
            sub_type = mat_spec.get("sub_type", "")
            params = mat_spec.get("params", {})
            bb = obj.get("bounding_box", {})
            bb_min = bb.get("min", [-0.5, -0.5, -0.5])
            bb_max = bb.get("max", [0.5, 0.5, 0.5])

            lines += [
                f"# Object: {label} ({mat_type}/{sub_type})",
                f"mesh_path_{safe_label} = r'{mesh_path}'",
                f"if os.path.exists(mesh_path_{safe_label}):",
                f"    bpy.ops.wm.obj_import(filepath=mesh_path_{safe_label})",
                f"    obj_{safe_label} = bpy.context.selected_objects[0]",
                f"    obj_{safe_label}.name = '{safe_label}'",
                f"else:",
                f"    # Fallback: create a cube placeholder",
                f"    bpy.ops.mesh.primitive_cube_add(",
                f"        size=1.0,",
                f"        location=({(bb_min[0]+bb_max[0])/2:.4f},",
                f"                  {(bb_min[1]+bb_max[1])/2:.4f},",
                f"                  {(bb_min[2]+bb_max[2])/2:.4f})",
                f"    )",
                f"    obj_{safe_label} = bpy.context.active_object",
                f"    obj_{safe_label}.name = '{safe_label}'",
                "",
                f"imported_objects['{label}'] = obj_{safe_label}",
                "",
            ]

            # Physics assignment
            lines += self._physics_block(
                safe_label=safe_label,
                mat_type=mat_type,
                sub_type=sub_type,
                params=params,
            )
            lines.append("")

        # ── Force Fields ──────────────────────────────────────────────────────
        if forces:
            lines += [
                "# ── Force fields ────────────────────────────────────────────────────",
                "",
            ]
            for i, force in enumerate(forces):
                lines += self._force_block(i, force)

        # ── Bake & Render ─────────────────────────────────────────────────────
        lines += [
            "",
            "# ── Bake physics ────────────────────────────────────────────────────────",
            "bpy.ops.ptcache.bake_all(bake=True)",
            "",
            "# ── Save .blend file ────────────────────────────────────────────────────",
            f"blend_path = r'{run_directory / 'simulation.blend'}'",
            "bpy.ops.wm.save_as_mainfile(filepath=blend_path)",
            "print(f'Simulation saved to: {blend_path}')",
            "",
            "# ── Optional: render animation ──────────────────────────────────────────",
            "# Uncomment to render:",
            f"# bpy.context.scene.render.filepath = r'{run_directory / 'render_'}/'",
            "# bpy.context.scene.render.image_settings.file_format = 'PNG'",
            "# bpy.ops.render.render(animation=True)",
            "",
        ]

        return "\n".join(lines)

    # ── Physics block generator ───────────────────────────────────────────────

    def _physics_block(
        self,
        safe_label: str,
        mat_type: str,
        sub_type: str,
        params: dict,
    ) -> list[str]:
        lines: list[str] = []
        ref = f"obj_{safe_label}"

        if mat_type == "rigid":
            density = params.get("density", 1000.0)
            friction = params.get("friction_dynamic", 0.4)
            restitution = params.get("restitution", 0.3)
            lines += [
                f"bpy.context.view_layer.objects.active = {ref}",
                f"bpy.ops.rigidbody.object_add()",
                f"{ref}.rigid_body.type = 'ACTIVE'",
                f"{ref}.rigid_body.mass = {density:.2f}",
                f"{ref}.rigid_body.friction = {friction:.3f}",
                f"{ref}.rigid_body.restitution = {restitution:.3f}",
                f"{ref}.rigid_body.collision_shape = 'CONVEX_HULL'",
            ]

        elif mat_type == "fluid":
            viscosity = params.get("viscosity", 0.001)
            lines += [
                f"bpy.context.view_layer.objects.active = {ref}",
                f"# Add fluid modifier",
                f"bpy.ops.object.modifier_add(type='FLUID')",
                f"{ref}.modifiers['Fluid'].fluid_type = 'FLOW'",
                f"flow = {ref}.modifiers['Fluid'].domain_settings",
                f"# Note: configure domain object separately",
            ]

        elif mat_type == "deformable":
            young_mod = params.get("young_modulus", 1e6)
            poisson = params.get("poisson_ratio", 0.45)
            damping = params.get("damping", 0.01)
            if sub_type in ("cloth", "fabric", "textile"):
                lines += [
                    f"bpy.context.view_layer.objects.active = {ref}",
                    f"bpy.ops.object.modifier_add(type='CLOTH')",
                    f"cloth = {ref}.modifiers['Cloth'].settings",
                    f"cloth.quality = 12",
                    f"cloth.mass = {params.get('density', 900) * 0.001:.4f}",
                    f"cloth.tension_stiffness = {young_mod / 1e6:.2f}",
                    f"cloth.air_damping = {damping:.4f}",
                ]
            else:
                lines += [
                    f"bpy.context.view_layer.objects.active = {ref}",
                    f"bpy.ops.object.modifier_add(type='SOFT_BODY')",
                    f"sb = {ref}.modifiers['Softbody'].settings",
                    f"sb.mass = {params.get('density', 900) * 0.001:.4f}",
                    f"sb.spring_length = 100",
                    f"sb.damping = {damping:.4f}",
                ]

        elif mat_type == "granular":
            lines += [
                f"# Granular: treated as rigid body particle",
                f"bpy.context.view_layer.objects.active = {ref}",
                f"bpy.ops.rigidbody.object_add()",
                f"{ref}.rigid_body.type = 'ACTIVE'",
                f"{ref}.rigid_body.mass = {params.get('density', 1600) * 0.0001:.4f}",
                f"{ref}.rigid_body.friction = {math.tan(math.radians(params.get('friction_angle', 30))):.4f}",
                f"{ref}.rigid_body.collision_shape = 'SPHERE'",
            ]

        return lines

    # ── Force block generator ─────────────────────────────────────────────────

    def _force_block(self, index: int, force: dict) -> list[str]:
        ftype = force.get("force_type", "impulse")
        target = force.get("target_object", "")
        direction = force.get("direction", [0, 0, -1])
        magnitude = force.get("magnitude", 1.0)
        start_time = force.get("start_time", 0.0)
        duration = force.get("duration", 0.0)
        desc = force.get("description", "")
        blender_type = FORCE_TYPE_TO_BLENDER.get(ftype, "FORCE")

        safe_target = target.replace(" ", "_").lower()
        lines = [
            f"# Force {index + 1}: {desc or ftype} on {target}",
            f"bpy.ops.object.effector_add(type='{blender_type}', location=("
            f"{direction[0]:.4f}, {direction[1]:.4f}, {direction[2]:.4f}))",
            f"ff_{index} = bpy.context.active_object",
            f"ff_{index}.name = 'force_{index}_{ftype}'",
            f"ff_{index}.field.strength = {magnitude:.4f}",
        ]

        if ftype in ("impulse",) and duration == 0:
            # Keyframe: on at frame 1, off at frame 2
            start_frame = max(1, int(start_time * 24))
            lines += [
                f"ff_{index}.field.strength = {magnitude:.4f}",
                f"ff_{index}.field.keyframe_insert('strength', frame={start_frame})",
                f"ff_{index}.field.strength = 0.0",
                f"ff_{index}.field.keyframe_insert('strength', frame={start_frame + 1})",
            ]
        elif duration > 0:
            end_frame = int((start_time + duration) * 24)
            start_frame = max(1, int(start_time * 24))
            lines += [
                f"ff_{index}.field.strength = 0.0",
                f"ff_{index}.field.keyframe_insert('strength', frame=1)",
                f"ff_{index}.field.strength = {magnitude:.4f}",
                f"ff_{index}.field.keyframe_insert('strength', frame={start_frame})",
                f"ff_{index}.field.strength = {magnitude:.4f}",
                f"ff_{index}.field.keyframe_insert('strength', frame={end_frame})",
                f"ff_{index}.field.strength = 0.0",
                f"ff_{index}.field.keyframe_insert('strength', frame={end_frame + 1})",
            ]

        lines.append("")
        return lines


# import needed for granular friction angle
import math