"""
utils/sam3d_wrapper.py — Local interface to SAM3D for mesh generation.

SAM3D performs object-level coarse-to-fine 3-D mesh reconstruction from a
masked 2-D crop.  This wrapper exposes ``generate_mesh()`` and returns a
serialisable dict so the pipeline can write results to JSON.

Real SAM3D installation:
    # Follow SAM-3D repo setup; checkpoint path set in cfg.SAM3D_CHECKPOINT
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import numpy as np

try:
    # Real SAM3D import — adjust to actual package name after installation
    import sam3d  # type: ignore[import]
    _SAM3D_AVAILABLE = True
except ImportError:
    _SAM3D_AVAILABLE = False

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
import config as cfg
from utils.shared import get_logger

_log = get_logger("sam3d_wrapper")
_model: Any = None


def _load_model() -> Any:
    global _model
    if _model is not None:
        return _model
    if not _SAM3D_AVAILABLE:
        _log.warning("SAM3D not installed — running in MOCK mode")
        return None
    _log.info("Loading SAM3D checkpoint: %s", cfg.SAM3D_CHECKPOINT)
    _model = sam3d.build_model(cfg.SAM3D_CHECKPOINT)
    _log.info("SAM3D ready")
    return _model


def generate_mesh(
    image_path: str,
    mask_data: dict,
    output_dir: Path,
    quality: str | None = None,
    refinement_hints: dict | None = None,
) -> dict:
    """
    Generate a 3-D mesh for a single masked object.

    Parameters
    ----------
    image_path:
        Path to the original RGB image.
    mask_data:
        A single mask dict as produced by ``sam2_wrapper.generate_masks()``.
    output_dir:
        Directory where the .obj (and optional .mtl) will be written.
    quality:
        ``"coarse"`` | ``"fine"`` | ``"adaptive"`` (default from config).
    refinement_hints:
        Optional dict from the Refinement Agent describing known issues
        (e.g. hole locations, overlap regions) so SAM3D can focus effort.

    Returns
    -------
    dict:
        {
          "label": str,
          "mesh_path": str,          # path to .obj file
          "vertex_count": int,
          "face_count": int,
          "bounding_box": {          # world-space AABB
              "min": [x, y, z],
              "max": [x, y, z],
          },
          "quality": str,
          "refinement_applied": bool,
        }
    """
    quality = quality or cfg.SAM3D_MESH_QUALITY
    model = _load_model()
    label = mask_data["label"]
    safe_label = label.replace(" ", "_").lower()
    mesh_path = output_dir / f"{safe_label}.obj"

    if model is None:
        # ── MOCK MODE ────────────────────────────────────────────────────────
        _log.warning("SAM3D MOCK: generating placeholder mesh for '%s'", label)
        _write_mock_obj(mesh_path, label)
        return {
            "label": label,
            "mesh_path": str(mesh_path),
            "vertex_count": 8,
            "face_count": 12,
            "bounding_box": {
                "min": [-0.5, -0.5, -0.5],
                "max": [0.5, 0.5, 0.5],
            },
            "quality": quality,
            "refinement_applied": refinement_hints is not None,
        }

    # ── REAL SAM3D ────────────────────────────────────────────────────────────
    from PIL import Image
    image = np.array(Image.open(image_path).convert("RGB"))

    # Decode binary mask
    from utils.sam2_wrapper import decode_mask
    h, w = image.shape[:2]
    binary_mask = decode_mask(mask_data["rle"], h, w)

    extra_kwargs: dict[str, Any] = {}
    if refinement_hints:
        extra_kwargs["hints"] = refinement_hints

    result = model.reconstruct(
        image=image,
        mask=binary_mask,
        quality=quality,
        **extra_kwargs,
    )

    # SAM3D returns a trimesh.Trimesh-like object
    mesh = result.mesh
    mesh.export(str(mesh_path))

    vmin = mesh.bounds[0].tolist()
    vmax = mesh.bounds[1].tolist()

    _log.info(
        "Mesh for '%s': %d verts, %d faces → %s",
        label, len(mesh.vertices), len(mesh.faces), mesh_path,
    )
    return {
        "label": label,
        "mesh_path": str(mesh_path),
        "vertex_count": len(mesh.vertices),
        "face_count": len(mesh.faces),
        "bounding_box": {"min": vmin, "max": vmax},
        "quality": quality,
        "refinement_applied": refinement_hints is not None,
    }


# ── Helpers ───────────────────────────────────────────────────────────────────

def _write_mock_obj(path: Path, label: str) -> None:
    """Write a minimal unit-cube .obj as a placeholder mesh."""
    obj_content = f"""# Mock mesh for: {label}
# Generated by sam3d_wrapper (MOCK mode)
v -0.5 -0.5  0.5
v  0.5 -0.5  0.5
v  0.5  0.5  0.5
v -0.5  0.5  0.5
v -0.5 -0.5 -0.5
v  0.5 -0.5 -0.5
v  0.5  0.5 -0.5
v -0.5  0.5 -0.5
f 1 2 3
f 1 3 4
f 5 7 6
f 5 8 7
f 1 5 6
f 1 6 2
f 2 6 7
f 2 7 3
f 3 7 8
f 3 8 4
f 4 8 5
f 4 5 1
"""
    path.write_text(obj_content)